FROM alpine:3.15.0 
LABEL  maintainer="boukheit fares" os="ubuntu" 
ENV CONTAINER_USER="boukheit fares" 
RUN adduser --disabled-password CONTAINER_USER
CMD ["echo", "hello-alpine, I'm BOUKHEIT Fares and this is a container for my first image"]
